Name = "Computational Cognitive Neuroscience"
About = "A complete, self-contained introduction to the field of Computational Cognitive Neuroscience, where computer models of the brain are used to understand a wide range of cognitive functions, including perception, attention, learning, memory, motor control, executive function, and language."
