// Code generated by 'yaegi extract github.com/compcogneuro/web/sims/stability'. DO NOT EDIT.

package yaegisims

import (
	"github.com/compcogneuro/web/sims/stability"
	"reflect"
)

func init() {
	Symbols["github.com/compcogneuro/web/sims/stability/stability"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Cycle":            reflect.ValueOf(stability.Cycle),
		"Embed":            reflect.ValueOf(stability.Embed),
		"Epoch":            reflect.ValueOf(stability.Epoch),
		"LayByNm":          reflect.ValueOf(stability.LayByNm),
		"LayNm":            reflect.ValueOf(stability.LayNm),
		"LayerParams":      reflect.ValueOf(&stability.LayerParams).Elem(),
		"LevelsN":          reflect.ValueOf(stability.LevelsN),
		"LevelsValues":     reflect.ValueOf(stability.LevelsValues),
		"ModesN":           reflect.ValueOf(stability.ModesN),
		"ModesValues":      reflect.ValueOf(stability.ModesValues),
		"PathParams":       reflect.ValueOf(&stability.PathParams).Elem(),
		"Start":            reflect.ValueOf(stability.Start),
		"StatsPhaseN":      reflect.ValueOf(stability.StatsPhaseN),
		"StatsPhaseValues": reflect.ValueOf(stability.StatsPhaseValues),
		"Step":             reflect.ValueOf(stability.Step),
		"Test":             reflect.ValueOf(stability.Test),
		"Train":            reflect.ValueOf(stability.Train),
		"Trial":            reflect.ValueOf(stability.Trial),

		// type definitions
		"Config":      reflect.ValueOf((*stability.Config)(nil)),
		"Levels":      reflect.ValueOf((*stability.Levels)(nil)),
		"LogConfig":   reflect.ValueOf((*stability.LogConfig)(nil)),
		"Modes":       reflect.ValueOf((*stability.Modes)(nil)),
		"ParamConfig": reflect.ValueOf((*stability.ParamConfig)(nil)),
		"RunConfig":   reflect.ValueOf((*stability.RunConfig)(nil)),
		"Sim":         reflect.ValueOf((*stability.Sim)(nil)),
		"StatsPhase":  reflect.ValueOf((*stability.StatsPhase)(nil)),
	}
}
